services:
  prefect-server:
    container_name: prefect-server
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - prefect

  prefect-worker-flow:
    container_name: prefect-worker-flow
    image:  main-flow:latest
    command: /bin/sh -c "sleep 15 && prefect worker start --pool 'flow-pool' --type process"
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
    depends_on:
      - prefect-server
    networks:
      - prefect


  prefect-worker-subflow:
    container_name: prefect-worker-subflow
    image: subflow:latest
    command: /bin/sh -c "sleep 10 && prefect worker start --pool 'subflow-pool' --type process"
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
    depends_on:
      - prefect-server
    networks:
      - prefect

networks:
  prefect:
